# Generated by Django 5.2.14 on 2026-06-02 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CentralUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('last_heartbeat', models.DateTimeField(blank=True, help_text='Czas ostatniego heartbeatu od Gateway.', null=True)),
                ('device_user', models.OneToOneField(help_text='Systemowe konto User powiązane z urządzeniem (do generowania JWT).', on_delete=django.db.models.deletion.CASCADE, related_name='central_unit', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PairingToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=16, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairing_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QueuedCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(help_text="ID węzła Pico, np. 'Pico_01'", max_length=64)),
                ('gpio', models.PositiveSmallIntegerField(help_text='Numer pinu GPIO')),
                ('command', models.CharField(choices=[('TURN_ON', 'Włącz'), ('TURN_OFF', 'Wyłącz'), ('TURN_ON_FOR', 'Włącz na czas'), ('WATER_PUMP_ON', 'Nawadniaj przez czas')], help_text='Nazwa komendy', max_length=32)),
                ('time', models.PositiveIntegerField(blank=True, help_text='Czas trwania w minutach (opcjonalny)', null=True)),
                ('status', models.CharField(choices=[('pending', 'Oczekujące'), ('delivered', 'Dostarczone')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('gateway', models.ForeignKey(help_text='Gateway do którego kierowana jest komenda.', on_delete=django.db.models.deletion.CASCADE, related_name='queued_commands', to='nodes.centralunit')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_commands', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ControllableNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(help_text="ID węzła końcowego, np. 'Pico_01'", max_length=64)),
                ('gpio', models.PositiveSmallIntegerField(blank=True, help_text='Numer pinu GPIO (tylko dla węzłów sterowanych)', null=True)),
                ('peripheral_type', models.CharField(blank=True, choices=[('LAMP', 'Lampa'), ('SPRINKLER', 'Zraszacz')], max_length=16, null=True)),
                ('sensor_type', models.CharField(blank=True, choices=[('temperature', 'Temperatura (°C)'), ('humidity', 'Wilgotność (%)'), ('light', 'Natężenie światła (lux)')], help_text='Typ czujnika przypisany przez użytkownika.', max_length=16, null=True)),
                ('label', models.CharField(blank=True, help_text="Przyjazna nazwa urządzenia nadana przez użytkownika, np. 'Lampa nad rozsadą'.", max_length=100, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peripherals', to='nodes.centralunit')),
            ],
            options={
                'unique_together': {('gateway', 'node_id')},
            },
        ),
        migrations.CreateModel(
            name='DeviceOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('viewer', 'Viewer')], default='admin', max_length=16)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='nodes.centralunit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_ownerships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'device')},
            },
        ),
        migrations.CreateModel(
            name='TelemetryReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(help_text="ID węzła, np. 'Pico_01'", max_length=64)),
                ('raw_payload', models.JSONField(blank=True, help_text='Surowy payload z węzła Pico, np. {"data": 23.5}', null=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('sensor_type', models.CharField(blank=True, choices=[('temperature', 'Temperatura (°C)'), ('humidity', 'Wilgotność (%)'), ('light', 'Natężenie światła (lux)')], help_text='Typ czujnika. Pobierany z konfiguracji węzła (ControllableNode), jeśli węzeł jest skonfigurowany.', max_length=16, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_readings', to='nodes.centralunit')),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['gateway', 'node_id', '-recorded_at'], name='nodes_telem_gateway_d94069_idx')],
            },
        ),
    ]
