# Generated by Django 5.2.14 on 2026-06-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='controllablenode',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Aktualny fizyczny/logiczny stan urządzenia (True = włączony, False = wyłączony).'),
        ),
    ]
