# Generated by Django 5.2.13 on 2026-05-06 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControllableNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(help_text="ID węzła końcowego, np. 'Pico_01'", max_length=64)),
                ('gpio', models.PositiveSmallIntegerField(help_text='Numer pinu GPIO')),
                ('peripheral_type', models.CharField(choices=[('LAMP', 'Lampa'), ('SPRINKLER', 'Zraszacz')], max_length=16)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peripherals', to='nodes.centralunit')),
            ],
            options={
                'unique_together': {('gateway', 'node_id', 'gpio')},
            },
        ),
        migrations.CreateModel(
            name='QueuedCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(help_text="Nazwa komendy, np. 'TURN_ON_FOR'", max_length=32)),
                ('time', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Oczekujące'), ('delivered', 'Dostarczone')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_commands', to=settings.AUTH_USER_MODEL)),
                ('peripheral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queued_commands', to='nodes.controllablenode')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
