# Generated by Django 5.2.13 on 2026-05-25 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0004_add_telemetryreading'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='telemetryreading',
            new_name='nodes_telem_gateway_d94069_idx',
            old_name='nodes_telemetr_gateway_idx',
        ),
    ]
