# Generated by Django 5.2.11 on 2026-04-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nazwa węzła')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Zarejestrowano')),
                ('last_seen', models.DateTimeField(blank=True, help_text='Czas ostatniej odebranej ramki MQTT od tego urządzenia.', null=True, verbose_name='Ostatnia transmisja')),
                ('is_sending', models.BooleanField(default=False, verbose_name='Nadaje dane')),
                ('delay_ms', models.IntegerField(blank=True, null=True, verbose_name='Interwał transmisji [ms]')),
                ('pins', models.JSONField(blank=True, default=dict, help_text='Słownik {numer_pinu: wartość} odzwierciedlający aktualny stan wyjść GPIO.', verbose_name='Stan pinów GPIO')),
                ('last_data', models.JSONField(blank=True, help_text='Ostatni payload odebrany na topic /device/<name>/data.', null=True, verbose_name='Ostatnie dane pomiarowe')),
            ],
            options={
                'verbose_name': 'Węzeł',
                'verbose_name_plural': 'Węzły',
                'ordering': ['-last_seen'],
            },
        ),
    ]
