# Generated by Django 5.2.11 on 2026-05-05 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_name', models.CharField(db_index=True, max_length=100, verbose_name='Węzeł')),
                ('command', models.CharField(choices=[('set_on', 'set_on'), ('set_off', 'set_off'), ('echo', 'echo'), ('get_pins', 'get_pins'), ('pin_on', 'pin_on'), ('pin_off', 'pin_off'), ('change_delay', 'change_delay'), ('get_format', 'get_format')], max_length=50, verbose_name='Komenda')),
                ('argument', models.IntegerField(blank=True, help_text='Wymagany dla: pin_on, pin_off, change_delay, get_format.', null=True, verbose_name='Argument (int)')),
                ('interval_seconds', models.PositiveIntegerField(help_text='Co ile sekund komenda ma być wysyłana.', verbose_name='Interwał [s]')),
                ('enabled', models.BooleanField(default=True, verbose_name='Aktywny')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='Ostatnie uruchomienie')),
            ],
            options={
                'verbose_name': 'Zaplanowana komenda',
                'verbose_name_plural': 'Zaplanowane komendy',
                'ordering': ['node_name', 'command'],
            },
        ),
    ]
