# Generated by Django 5.2.11 on 2026-05-05 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0002_scheduled_command'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='pin_formats',
            field=models.JSONField(blank=True, default=dict, help_text='Słownik {numer_pinu: {type, unit, min, max}} z metadanymi pomiarów.', verbose_name='Formaty pinów sensorycznych'),
        ),
    ]
