# Generated by Django 5.2.11 on 2026-05-05 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0003_pin_formats'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='pin_values',
            field=models.JSONField(blank=True, default=dict, help_text='Słownik {numer_pinu: ostatnia_wartość} aktualizowany przy każdym pomiarze.', verbose_name='Ostatnie wartości pinów'),
        ),
    ]
