# Generated by Django 5.2.11 on 2026-05-16 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0004_pin_values'),
    ]

    operations = [
        migrations.CreateModel(
            name='GatewayToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access', models.TextField(blank=True, null=True, verbose_name='Access Token')),
                ('refresh', models.TextField(blank=True, null=True, verbose_name='Refresh Token')),
                ('device_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Device ID')),
            ],
            options={
                'verbose_name': 'Token Gatewaya',
                'verbose_name_plural': 'Tokeny Gatewaya',
            },
        ),
    ]
