# Generated by Django 5.2.11 on 2026-05-16 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0005_gatewaytoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='pin_formats',
        ),
        migrations.RemoveField(
            model_name='node',
            name='pin_values',
        ),
        migrations.CreateModel(
            name='NodePin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_number', models.IntegerField(verbose_name='Numer pinu')),
                ('pin_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Typ pomiaru')),
                ('unit', models.CharField(blank=True, max_length=20, null=True, verbose_name='Jednostka')),
                ('min_value', models.FloatField(blank=True, null=True, verbose_name='Wartość min')),
                ('max_value', models.FloatField(blank=True, null=True, verbose_name='Wartość max')),
                ('last_value', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ostatnia wartość')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_pins', to='nodes.node', verbose_name='Węzeł')),
            ],
            options={
                'verbose_name': 'Pin sensoryczny',
                'verbose_name_plural': 'Piny sensoryczne',
                'ordering': ['node', 'pin_number'],
                'unique_together': {('node', 'pin_number')},
            },
        ),
    ]
