# Generated by Django 5.2.11 on 2026-05-16 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0006_remove_node_pin_formats_remove_node_pin_values_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='sensor_last_value',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ostatnia wartość'),
        ),
        migrations.AddField(
            model_name='node',
            name='sensor_max_value',
            field=models.FloatField(blank=True, null=True, verbose_name='Wartość max'),
        ),
        migrations.AddField(
            model_name='node',
            name='sensor_min_value',
            field=models.FloatField(blank=True, null=True, verbose_name='Wartość min'),
        ),
        migrations.AddField(
            model_name='node',
            name='sensor_pin',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pin sensoryczny'),
        ),
        migrations.AddField(
            model_name='node',
            name='sensor_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Typ pomiaru'),
        ),
        migrations.AddField(
            model_name='node',
            name='sensor_unit',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Jednostka'),
        ),
        migrations.DeleteModel(
            name='NodePin',
        ),
    ]
