# Generated by Django 5.2.11 on 2026-05-16 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0007_node_sensor_last_value_node_sensor_max_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='logs',
            field=models.JSONField(blank=True, default=list, verbose_name='Logi urządzenia'),
        ),
        migrations.AlterField(
            model_name='scheduledcommand',
            name='command',
            field=models.CharField(choices=[('set_on', 'set_on'), ('set_off', 'set_off'), ('echo', 'echo'), ('get_pins', 'get_pins'), ('get_format', 'get_format'), ('pin_on', 'pin_on'), ('pin_off', 'pin_off'), ('change_delay', 'change_delay')], max_length=50, verbose_name='Komenda'),
        ),
    ]
