# Generated by Django 5.2.11 on 2026-05-16 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0008_node_logs_alter_scheduledcommand_command'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='sensor_kind',
            field=models.CharField(blank=True, choices=[('temperature', 'Temperatura (°C)'), ('humidity', 'Wilgotność (%)'), ('light', 'Natężenie światła (lux)')], max_length=50, null=True, verbose_name='Kategoria pomiaru'),
        ),
    ]
