# Generated by Django 5.2.11 on 2026-05-16 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0009_node_sensor_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('switch_id', models.IntegerField(verbose_name='ID Switcha / Pin')),
                ('state', models.BooleanField(default=False, verbose_name='Stan')),
                ('switch_type', models.CharField(choices=[('LAMP', 'Lampa'), ('SPRINKLER', 'Zraszacz')], default='LAMP', max_length=50, verbose_name='Typ')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='switches', to='nodes.node', verbose_name='Węzeł')),
            ],
            options={
                'verbose_name': 'Przełącznik',
                'verbose_name_plural': 'Przełączniki',
                'unique_together': {('node', 'switch_id')},
            },
        ),
    ]
